### ISSUE TITLE
Spaces deletion on search bar

### ISSUE THREAD

**Issue by liaozhuzhu** [acm-uiowa/uigrades-old#10]
spaces entered by user sometimes get deleted when searching for a course

**Comment by liaozhuzhu** [comment]
i think i fixed it but might need more parties to test this

**Comment by ambha21** [comment]
I believe this is still an issue. Try this, search "     Accounting" then delete the "Accounting" portion.

**Comment by liaozhuzhu** [comment]
i can't seem to duplicate any issues there. what happens when run?

One test case i kept seeing this bug (rarely if any now) is a search query like "algorithms spring 2023"

**Comment by ambha21** [comment]
When run, it just deletes the spaces. Your example also works. It basically just auto deletes spaces after the word after the space(s) has been deleted
